name: GPG Install
on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - id: install-secret-key
      name: Install gpg secret key
      run: |
        # Install gpg secret key
        cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
        # Verify gpg secret key
        gpg --list-secret-keys --keyid-format LONG
